# CI – Build, Push & Package using GitHub Actions
name: CI – Build, Push & Package

on:
  # Trigger on pushes to main, PRs against main, or manual dispatch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    # Use a Windows runner to support Windows containers
    runs-on: windows-latest
    env:
      # Lowercase the GitHub owner/repo string for a valid Docker image name
      IMAGE_NAME: ghcr.io/${{ toLower(github.repository) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetch repository contents into GITHUB_WORKSPACE

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2  # Authenticate Docker to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GITHUB_TOKEN has write permissions
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image (with layer cache)
        uses: docker/build-push-action@v4  # Build, cache, and push your image
        with:
          context: .                   # Build context is repository root
          file: Dockerfile            # Path to your Dockerfile
          push: true                  # Push the resulting image tags
          tags: |
            ${{ env.IMAGE_NAME }}:latest      # 'latest' tag for convenience
            ${{ env.IMAGE_NAME }}:${{ github.sha }}  # SHA tag for exact reproducibility
          cache-from: |
            type=registry,ref=${{ env.IMAGE_NAME }}:cache  # Pull existing layer cache
          cache-to: |
            type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max  # Update cache in registry

      - name: Run build script in container
        run: |
          # Use the SHA-specific tag to run the exact image we just built
          docker run --rm \
            --mount type=bind,source="${{ github.workspace }}",target=C:\workspace \
            -w C:\workspace \
            ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            powershell -NoLogo -ExecutionPolicy Bypass \
                       -File .\app\build.ps1 \
                       -Config Release \
                       -BuildDir C:\workspace

      - name: Build documentation in container
        run: |
          # Generate HTML docs using Sphinx in the same exact image
          docker run --rm \
            --mount type=bind,source="${{ github.workspace }}",target=C:\workspace \
            -w C:\workspace \
            ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            powershell -NoLogo -ExecutionPolicy Bypass \
                       -Command "sphinx-build -M html docs docs\_build"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Persist compiled binaries
        with:
          name: binaries
          path: app/build/install/**

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v3  # Persist generated docs
        with:
          name: docs
          path: docs/_build/html/**
